### ISSUE TITLE
/api: 404 not found.

### ISSUE THREAD

**Issue by lelman005** [m7mark/telegram-bot-vercel-boilerplate#1]
I forked your repo and imported to Vercel, added BOT_TOKEN variables within double quotes "", deployed and it doesn't work! 

/api
500
production
404: Not Found

I know for a fact that the code is alright, it is just that i am messing up somewhere. I am not familiar with Vercel so can't really fix it and I haven't found any solution elsewhere on the Internet too. I will highly appreciate your help!
P.S. i tried deploying on different Vercel projects with different Bot Tokens several times with tweaks here and there like promote to production, added VERCEL_URL manually, changed Deployment Protection and couple of more things.

**Comment by sollidy** [comment]
Hello! Please add BOT_TOKEN without quotes on Versel Dashboard: Settings > Environment Variables
