### ISSUE TITLE
Deployed successfully but bot is not responding

### ISSUE THREAD

**Issue by wobsoriano** [m7mark/telegram-bot-vercel-boilerplate#2]
Hi, I forked this project and deployed it to Vercel (BOT_TOKEN env is added) and it was a success. The bot, on the other hand, is not responding. Is there any additional step I need to add to my vercel config?

![Screenshot 2023-11-26 at 8 41 35 PM](https://github.com/sollidy/telegram-bot-vercel-boilerplate/assets/13049130/52369081-dbe3-4da8-a28a-0cd91bc006da)

local dev works, though.

**Comment by sollidy** [comment]
Hello! try to turn off `Vercel Authentication`
![prod](https://github.com/sollidy/telegram-bot-vercel-boilerplate/assets/70297692/f7ac55c3-6b8b-4ca8-b9aa-9691816bdaf6)

**Comment by wobsoriano** [comment]
Thanks! It's working now.
